# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
orbs:
  heroku: circleci/heroku@1.0.0
jobs:
  build:
    working_directory: ~/focushift
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: POSTGRES_DB
          POSTGRES_PASSWORD: POSTGRES_PASSWORD
    steps:
      - checkout
      # Restore Cached Dependencies
      - run: gem install bundler
      - type: cache-restore
        name: Restore bundle cache
        key: focushift-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - type: cache-save
        name: Store bundle cache
        key: focushift-{{ checksum "Gemfile.lock" }}
        paths:
            - vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Setup the database
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:prepare
      - run: 
          name: run rubocop
          command: |
            bundle exec rubocop
  deploy:
    executor: heroku/default # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - checkout
      - heroku/install # Runs the heroku install command, if necessary.
      - heroku/deploy-via-git # Deploys branch to Heroku via git push.
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - deploy:
        requires:
          - build