# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  test:
    post:
      - bundle exec rubocop
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.3

    working_directory: ~/repo

    steps:
      - checkout
      - ruby-linter/rubocop:
          files: app/**/*.rb lib/**/*.rb config/**/*.rb spec/**/*.rb script/**/*.rb
          report_dir: $CIRCLE_TEST_REPORTS

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
orbs:
  ruby-linter: amyroi/ruby-linter@1.0.0